language: python
python:
  - "3.8"
cache: pip
before_install:
  - sudo apt-get install -y libgsl-dev
  - pip install NRSur7dq2
install:
  - pip install .
script:
  - py.test
addons:
  ssh_known_hosts:
      - bitbucket.org
